# Generated by Django 4.0.6 on 2022-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('number_of_questions', models.PositiveIntegerField()),
                ('time', models.IntegerField(help_text='Quiz duration in minutes')),
                ('passing_score', models.PositiveIntegerField(help_text='Minimum required scooree to pass')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
