# Generated by Django 4.0.6 on 2022-07-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(help_text='Minimum required % to pass'),
        ),
    ]
